# https://content-security-policy.com/
# https://content-security-policy.com/examples/netlify/

[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.13.1"
  NPM_VERSION = "8.1.2"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "https://www.datenga.org;"
    # Content-Security-Policy = "default-src 'self' 'sha384-CP0pwD2GW8dy635yS5s6VaqJX7b9DS5puV/X18bgSmR2xaePsyP78hLM8yIqXYCA'; script-src 'self' unpkg.com identity.netlify.com;"
    Content-Security-Policy = "default-src 'self' unpkg.com identity.netlify.com doks-child-theme.netlify.app 'unsafe-inline' 'unsafe-eval';"  # TODO: must select actual nonces for security


